import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Button from "../components/Button";
import Menu0 from "./menu0";
import Menu from "./menu";
import Menu2 from "./menu2";
import Menu3 from "./menu3";
import { margin } from "@mui/system";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link
          rel="stylesheet"
          as="style"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css"
        />

        {/* <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Press+Start+2P&display=swap" rel="stylesheet">  */}
      </Head>

      <main className={styles.main}>
        {/* <Button src="/vertical" name="vertical" />
        <Button src="/horizontal" name="horizontal" /> */}
        {/* <Button src="/complex" name="complex" /> */}
        {/* <Button src="/scrolltelling" name="scrolltelling" /> */}
        {/* <Button src="/normal" name="normal" /> */}
        {/* <Mailer /> */}
        {/* <Button src="/A" name="A" />
        <Button src="/B" name="B" /> */}
        <h1>아재아재 MOVE?</h1>
        <article
          style={{ padding: "0", margin: "0" }}
          className="grid grid-rows-2 grid-cols-5"
        >
          <Menu0 className="col-span-1" />
          <br />
          <Menu className="col-span-1" />
          <br />
          <Menu2 className="col-span-1" />
          <br />
          <Menu3 className="col-span-3" />
        </article>

        <article>{}</article>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
